pytlanguage: python

python:
  - 3.6

services:
- docker

before_install:
  - pip install codecov coverage
  - pip install -r test_requirements.txt

install:
  - pip install -r requirements.txt
  - pip install -r consul-requirements.txt

script:
  - PYTHONPATH=. coverage run -m unittest discover -v -s thriftybuilder/tests
  - coverage run setup.py -q install
  - PYTHONPATH=. coverage run thriftybuilder/cli/main.py -h
  - coverage combine -a
  - coverage report

after_success:
  - codecov
