language: python

python:
  - 3.6

services:
  - docker

before_install:
  - pip install codecov coverage

install:
  - pip --disable-pip-version-check install -U -r test_requirements.txt
  - pip --disable-pip-version-check install -U -r requirements.txt
  - pip --disable-pip-version-check install -U -r consul-requirements.txt

script:
  - ./run-tests.sh

after_success:
  - codecov
